USE [master]
GO

/****** Object:  Database [TLGPizza]    Script Date: 9/13/2017 1:39:26 PM ******/
CREATE DATABASE [TLGPizza]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TLGPizza', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\TLGPizza.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TLGPizza_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\TLGPizza_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TLGPizza] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TLGPizza].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TLGPizza] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TLGPizza] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TLGPizza] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TLGPizza] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TLGPizza] SET ARITHABORT OFF 
GO

ALTER DATABASE [TLGPizza] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TLGPizza] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TLGPizza] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TLGPizza] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TLGPizza] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TLGPizza] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TLGPizza] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TLGPizza] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TLGPizza] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TLGPizza] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TLGPizza] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TLGPizza] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TLGPizza] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TLGPizza] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TLGPizza] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TLGPizza] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TLGPizza] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TLGPizza] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TLGPizza] SET  MULTI_USER 
GO

ALTER DATABASE [TLGPizza] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TLGPizza] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TLGPizza] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TLGPizza] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TLGPizza] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TLGPizza] SET QUERY_STORE = OFF
GO

USE [TLGPizza]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TLGPizza] SET  READ_WRITE 
GO

